//
// Generated file, do not edit! Created by opp_msgtool 6.1 from DNP3Packet.msg.
//

#ifndef __DNP3PACKET_M_H
#define __DNP3PACKET_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0601
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif

class Dnp3Packet;
/**
 * Class generated from <tt>DNP3Packet.msg:16</tt> by opp_msgtool.
 * <pre>
 * //
 * // This program is free software: you can redistribute it and/or modify
 * // it under the terms of the GNU Lesser General Public License as published by
 * // the Free Software Foundation, either version 3 of the License, or
 * // (at your option) any later version.
 * // 
 * // This program is distributed in the hope that it will be useful,
 * // but WITHOUT ANY WARRANTY; without even the implied warranty of
 * // MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * // GNU Lesser General Public License for more details.
 * // 
 * // You should have received a copy of the GNU Lesser General Public License
 * // along with this program.  If not, see http://www.gnu.org/licenses/.
 * //
 * packet Dnp3Packet
 * {
 *     int meterId = -1;
 *     int seq = 0;
 *     string msgType;
 *     bool burst = false;
 * }
 * </pre>
 */
class Dnp3Packet : public ::omnetpp::cPacket
{
  protected:
    int meterId = -1;
    int seq = 0;
    omnetpp::opp_string msgType;
    bool burst = false;

  private:
    void copy(const Dnp3Packet& other);

  protected:
    bool operator==(const Dnp3Packet&) = delete;

  public:
    Dnp3Packet(const char *name=nullptr, short kind=0);
    Dnp3Packet(const Dnp3Packet& other);
    virtual ~Dnp3Packet();
    Dnp3Packet& operator=(const Dnp3Packet& other);
    virtual Dnp3Packet *dup() const override {return new Dnp3Packet(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual int getMeterId() const;
    virtual void setMeterId(int meterId);

    virtual int getSeq() const;
    virtual void setSeq(int seq);

    virtual const char * getMsgType() const;
    virtual void setMsgType(const char * msgType);

    virtual bool getBurst() const;
    virtual void setBurst(bool burst);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const Dnp3Packet& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, Dnp3Packet& obj) {obj.parsimUnpack(b);}


namespace omnetpp {

template<> inline Dnp3Packet *fromAnyPtr(any_ptr ptr) { return check_and_cast<Dnp3Packet*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __DNP3PACKET_M_H

